# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hXzQghyWDnWFVKl9biNLuWOiI4jaKnf6
"""

import numpy as np

import pandas as pd

import matplotlib.pyplot as plt

"""# reading the data file

"""

df = pd.read_csv("/content/housing.csv")

print(df)

"""#printing the shape"""

print (df.shape)

print(df.head(10))

print(df.tail(10))

print(df.columns)

print(df['total_rooms'])

X = df['total_rooms'].head(150).values.reshape(-1,1)

y = df['median_house_value'].head(150).values.reshape(-1, 1)

plt.scatter(X, y)
plt.xlabel("Total Rooms")
plt.ylabel("Median House Value")
plt.title("Scatter Plot of Total Rooms vs. Median House Value")
plt.show()

print(df.describe())

